info:
  build:
    artifact: ${project.artifactId}
    description: ${project.description}
    name: ${project.name}
    version: ${project.version}
    time: ${build.time}

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /

server:
  zookeeper: 192.168.16.246:2181
  mysql: 127.0.0.1:3306
  redis: 192.168.16.246
  redis-port: 6379
  port: 19002
  ## 等待队列长度，默认100。
  tomcat:
    accept-count: 500
    ## 最大工作线程数，默认200。（4核8g内存，线程数经验值800，操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。）
    max-threads: 300
    ## 最小工作空闲线程数，默认10。（适当增大一些，以便应对突然增长的访问量）
    min-spare-threads: 100
#定时任务
elasticjob:
  serverList: ${server.zookeeper}
  namespace: gateway_elasticjob

spring:
  application:
    name: api-gateway
    jackson:
      date-format: yyyy/MM/dd HH:mm:ss
      time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  session:
    store-type: redis
    timeout: 30m
  redis:
    host: ${server.redis}
    port: ${server.redis-port}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${server.mysql}/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root123
    initialSize: 30
    minIdle: 30
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 30
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

dubbo:
  application:
    name: ${spring.application.name}
  consumer:
    check: false
  protocol:
    port: 19003
    name: dubbo
  registry:
    address: zookeeper://${server.zookeeper}

mybatis:
  typeAliasesPackage: com.zhiyong.gateway.dal.domain
  mapperLocations: classpath:/mapper/*.xml

logging:
  level:
    root: info
  file:
    path: './logs'
